/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Principal;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

import SubVentanas.frmCambioDescClienteHabi;
import SubVentanas.frmCambioPrecioHab;
import SubVentanas.frmDireccionIngresoCliente;

/**
 *
 * @author Nicolas
 */
public class frmAdministrador extends javax.swing.JPanel {

    /**
     * Creates new form frmAdministrador
     */
    public frmAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtAdministrador = new javax.swing.JLabel();
        Button_GestionarClientes = new javax.swing.JButton();
        Button_GestionarHabitaciones = new javax.swing.JButton();
        Button_GestionarUsuarios = new javax.swing.JButton();
        Button_GestionarServicios = new javax.swing.JButton();
        Button_TareasOtrosPerfiles = new javax.swing.JButton();
        Button_GestionarReservas = new javax.swing.JButton();
        Button_GestionarIngresos = new javax.swing.JButton();
        jButton_CerrarSesion = new javax.swing.JButton();
        Button_IngresoCliente = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtAdministrador.setBackground(new java.awt.Color(255, 255, 255));
        txtAdministrador.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        txtAdministrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagene/favicon.png"))); // NOI18N
        txtAdministrador.setText("MENU ADMINISTRADOR");

        Button_GestionarClientes.setBackground(new java.awt.Color(204, 204, 255));
        Button_GestionarClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Button_GestionarClientes.setText("GESTIONAR CLIENTES");
        Button_GestionarClientes.setBorder(null);
        Button_GestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GestionarClientesActionPerformed(evt);
            }
        });

        Button_GestionarHabitaciones.setBackground(new java.awt.Color(204, 204, 255));
        Button_GestionarHabitaciones.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Button_GestionarHabitaciones.setText("GESTIONAR HABITACIONES");
        Button_GestionarHabitaciones.setBorder(null);
        Button_GestionarHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GestionarHabitacionesActionPerformed(evt);
            }
        });

        Button_GestionarUsuarios.setBackground(new java.awt.Color(204, 204, 255));
        Button_GestionarUsuarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Button_GestionarUsuarios.setText("GESTIONAR USUARIOS");
        Button_GestionarUsuarios.setBorder(null);
        Button_GestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GestionarUsuariosActionPerformed(evt);
            }
        });

        Button_GestionarServicios.setBackground(new java.awt.Color(204, 204, 255));
        Button_GestionarServicios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Button_GestionarServicios.setText("GESTIONAR SERVICIOS");
        Button_GestionarServicios.setBorder(null);
        Button_GestionarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GestionarServiciosActionPerformed(evt);
            }
        });

        Button_TareasOtrosPerfiles.setBackground(new java.awt.Color(204, 204, 255));
        Button_TareasOtrosPerfiles.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Button_TareasOtrosPerfiles.setText("ACCESO TOTAL");
        Button_TareasOtrosPerfiles.setBorder(null);
        Button_TareasOtrosPerfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TareasOtrosPerfilesActionPerformed(evt);
            }
        });

        Button_GestionarReservas.setBackground(new java.awt.Color(204, 204, 255));
        Button_GestionarReservas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Button_GestionarReservas.setText("GESTIONAR RESERVAS");
        Button_GestionarReservas.setBorder(null);
        Button_GestionarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GestionarReservasActionPerformed(evt);
            }
        });

        Button_GestionarIngresos.setBackground(new java.awt.Color(204, 204, 255));
        Button_GestionarIngresos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Button_GestionarIngresos.setText("GESTIONAR INGRESOS");
        Button_GestionarIngresos.setBorder(null);
        Button_GestionarIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GestionarIngresosActionPerformed(evt);
            }
        });

        jButton_CerrarSesion.setBackground(new java.awt.Color(204, 204, 255));
        jButton_CerrarSesion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton_CerrarSesion.setText("Cerrar Sesion");
        jButton_CerrarSesion.setBorder(null);
        jButton_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CerrarSesionActionPerformed(evt);
            }
        });

        Button_IngresoCliente.setBackground(new java.awt.Color(204, 204, 255));
        Button_IngresoCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Button_IngresoCliente.setText("INGRESAR CLIENTE");
        Button_IngresoCliente.setBorder(null);
        Button_IngresoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_IngresoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Button_GestionarHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_GestionarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(txtAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Button_TareasOtrosPerfiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_GestionarServicios, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_GestionarIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_IngresoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_GestionarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_GestionarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_GestionarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_GestionarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_GestionarHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_GestionarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_GestionarServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_GestionarIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_TareasOtrosPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_IngresoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>                        

    private void Button_GestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        JFrame CambioDescClienteHabi = new JFrame("CambioDescClienteHabi");
        CambioDescClienteHabi.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        CambioDescClienteHabi.add(new frmCambioDescClienteHabi());
        CambioDescClienteHabi.pack();
        CambioDescClienteHabi.setLocationRelativeTo(null);
        CambioDescClienteHabi.setVisible(true);

        JFrame Administrador = (JFrame) SwingUtilities.getWindowAncestor(this);
        Administrador.dispose();
    }                                                        

    private void Button_GestionarHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        JFrame GestionPrecioHab = new JFrame("Gestion Precio Habitaciones");
        GestionPrecioHab.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        GestionPrecioHab.add(new frmCambioPrecioHab());
        GestionPrecioHab.pack();
        GestionPrecioHab.setLocationRelativeTo(null);
        GestionPrecioHab.setVisible(true);

        JFrame Administrador = (JFrame) SwingUtilities.getWindowAncestor(this);
        Administrador.dispose();
    }                                                            

    private void Button_GestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void Button_GestionarServiciosActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
    }                                                         

    private void Button_TareasOtrosPerfilesActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // TODO add your handling code here:
    }                                                          

    private void Button_GestionarReservasActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void Button_GestionarIngresosActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void jButton_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        JFrame Login = new JFrame("Login");
        Login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Login.add(new frmlogin());
        Login.pack();
        Login.setLocationRelativeTo(null);
        Login.setVisible(true);

        JFrame Administrador = (JFrame) SwingUtilities.getWindowAncestor(this);
        Administrador.dispose();
    }                                                    

    private void Button_IngresoClienteActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        JFrame IngresoCliente = new JFrame("Ingreso Cliente");
        IngresoCliente.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        IngresoCliente.add(new frmDireccionIngresoCliente());
        IngresoCliente.pack();
        IngresoCliente.setLocationRelativeTo(null);
        IngresoCliente.setVisible(true);

        JFrame Recepcionista = (JFrame) SwingUtilities.getWindowAncestor(this);
        Recepcionista.dispose();
    }                                                     


    // Variables declaration - do not modify                     
    private javax.swing.JButton Button_GestionarClientes;
    private javax.swing.JButton Button_GestionarHabitaciones;
    private javax.swing.JButton Button_GestionarIngresos;
    private javax.swing.JButton Button_GestionarReservas;
    private javax.swing.JButton Button_GestionarServicios;
    private javax.swing.JButton Button_GestionarUsuarios;
    private javax.swing.JButton Button_IngresoCliente;
    private javax.swing.JButton Button_TareasOtrosPerfiles;
    private javax.swing.JButton jButton_CerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtAdministrador;
    // End of variables declaration                   
}
