/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Principal;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Nicolas
 */
public class frmCajero extends javax.swing.JPanel {

    /**
     * Creates new form frmCajero
     */
    public frmCajero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMenuCajero = new javax.swing.JLabel();
        Button_Cerrrarcuenta = new javax.swing.JButton();
        Button_RegistrarCheckout = new javax.swing.JButton();
        jButton_CerrarSesion = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtMenuCajero.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        txtMenuCajero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMenuCajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagene/favicon.png"))); // NOI18N
        txtMenuCajero.setText("MENU CAJERO");

        Button_Cerrrarcuenta.setBackground(new java.awt.Color(204, 204, 255));
        Button_Cerrrarcuenta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Button_Cerrrarcuenta.setText("CERRAR CUENTA");
        Button_Cerrrarcuenta.setBorder(null);
        Button_Cerrrarcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CerrrarcuentaActionPerformed(evt);
            }
        });

        Button_RegistrarCheckout.setBackground(new java.awt.Color(204, 204, 255));
        Button_RegistrarCheckout.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Button_RegistrarCheckout.setText("REGISTRAR CHECKOUT");
        Button_RegistrarCheckout.setBorder(null);
        Button_RegistrarCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RegistrarCheckoutActionPerformed(evt);
            }
        });

        jButton_CerrarSesion.setBackground(new java.awt.Color(204, 204, 255));
        jButton_CerrarSesion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton_CerrarSesion.setText("Cerrar Sesion");
        jButton_CerrarSesion.setBorder(null);
        jButton_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_Cerrrarcuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(Button_RegistrarCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(txtMenuCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtMenuCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_RegistrarCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_Cerrrarcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    private void Button_CerrrarcuentaActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void Button_RegistrarCheckoutActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void jButton_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        JFrame Login = new JFrame("Login");
        Login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Login.add(new frmlogin());
        Login.pack();
        Login.setLocationRelativeTo(null);
        Login.setVisible(true);

        JFrame loginFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        loginFrame.dispose();
    }                                                    


    // Variables declaration - do not modify                     
    private javax.swing.JButton Button_Cerrrarcuenta;
    private javax.swing.JButton Button_RegistrarCheckout;
    private javax.swing.JButton jButton_CerrarSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtMenuCajero;
    // End of variables declaration                   
}
