/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SubVentanas;

import java.awt.event.ActionEvent;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

import Principal.frmAdministrador;


/**
 *
 * @author Nicolas
 */
public class frmDireccionIngresoCliente extends javax.swing.JPanel {

    /**
     * Creates new form frmDireccionIngresoCliente
     */
    public frmDireccionIngresoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIngresoCliente = new javax.swing.JLabel();
        jButtonClienteHabitual = new javax.swing.JButton();
        jButtonClienteEsporadico = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtIngresoCliente.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        txtIngresoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIngresoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagene/favicon.png"))); // NOI18N
        txtIngresoCliente.setText("INGRESO CLIENTE");

        jButtonClienteHabitual.setBackground(new java.awt.Color(204, 204, 255));
        jButtonClienteHabitual.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButtonClienteHabitual.setText("INGRESAR CLIENTE HABITUAL");
        jButtonClienteHabitual.setBorder(null);
        jButtonClienteHabitual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteHabitualActionPerformed(evt);
            }

        });

        jButtonClienteEsporadico.setBackground(new java.awt.Color(204, 204, 255));
        jButtonClienteEsporadico.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButtonClienteEsporadico.setText("INGRESAR CLIENTE ESPORADICO");
        jButtonClienteEsporadico.setBorder(null);
        jButtonClienteEsporadico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteEsporadicoActionPerformed(evt);
            }
        });

        jButtonAtras.setBackground(new java.awt.Color(204, 204, 255));
        jButtonAtras.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButtonAtras.setText("ATRAS");
        jButtonAtras.setBorder(null);
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonClienteEsporadico, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClienteHabitual, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(txtIngresoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtIngresoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButtonClienteHabitual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonClienteEsporadico, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    private void jButtonClienteEsporadicoActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        JFrame ClienteEsporadico = new JFrame("Administrador");
        ClienteEsporadico.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ClienteEsporadico.add(new frmClienteEsporadico());
        ClienteEsporadico.pack();
        ClienteEsporadico.setLocationRelativeTo(null);
        ClienteEsporadico.setVisible(true);

        JFrame ClienteFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        ClienteFrame.dispose();
    }

    private void jButtonClienteHabitualActionPerformed(ActionEvent evt) {
        JFrame ClienteEsporadico = new JFrame("Administrador");
        ClienteEsporadico.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ClienteEsporadico.add(new frmIngresoClienteHabitual());
        ClienteEsporadico.pack();
        ClienteEsporadico.setLocationRelativeTo(null);
        ClienteEsporadico.setVisible(true);

        JFrame ClienteFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        ClienteFrame.dispose();
    }

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {                                             
        JFrame ClienteEsporadico = new JFrame("Administrador");
        ClienteEsporadico.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ClienteEsporadico.add(new frmAdministrador());
        ClienteEsporadico.pack();
        ClienteEsporadico.setLocationRelativeTo(null);
        ClienteEsporadico.setVisible(true);

        JFrame ClienteDireccionFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        ClienteDireccionFrame.dispose();
    }                                            


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonClienteEsporadico;
    private javax.swing.JButton jButtonClienteHabitual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtIngresoCliente;
    // End of variables declaration                   
}
