/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SubVentanas;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Nicolas
 */
public class frmIngresoClienteHabitual extends javax.swing.JPanel {

    /**
     * Creates new form frmIngresoClienteHabitual
     */
    public frmIngresoClienteHabitual() {
        initComponents();
        jComboBoxTipoClienteHabitual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona Natural", "Corporativo" }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtIngresoCliente = new javax.swing.JLabel();
        jTextField_NombreClienteHab = new javax.swing.JTextField();
        Label_NombreClienteHab = new javax.swing.JLabel();
        Label_CedulaClienteHab = new javax.swing.JLabel();
        jTextField_TelefonoClienteHab = new javax.swing.JTextField();
        Label_TelefonoClienteHab = new javax.swing.JLabel();
        jTextField_CedulaClienteHab = new javax.swing.JTextField();
        jButton_IngresarClienteHab = new javax.swing.JButton();
        jButton_Atras = new javax.swing.JButton();
        Label_NombreCliente1 = new javax.swing.JLabel();
        Label_DescuentoClienteHabitual = new javax.swing.JLabel();
        jTextField_DescuentoClienteHab = new javax.swing.JTextField();
        jComboBoxTipoClienteHabitual = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtIngresoCliente.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        txtIngresoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIngresoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagene/favicon.png"))); // NOI18N
        txtIngresoCliente.setText("INGRESO CLIENTE HABITUAL");

        Label_NombreClienteHab.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Label_NombreClienteHab.setText("NOMBRE");

        Label_CedulaClienteHab.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Label_CedulaClienteHab.setText("CEDULA");

        Label_TelefonoClienteHab.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Label_TelefonoClienteHab.setText("TELEFONO");

        jButton_IngresarClienteHab.setBackground(new java.awt.Color(204, 204, 255));
        jButton_IngresarClienteHab.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton_IngresarClienteHab.setText("INGRESAR");
        jButton_IngresarClienteHab.setBorder(null);
        jButton_IngresarClienteHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IngresarClienteHabActionPerformed(evt);
            }
        });

        jButton_Atras.setBackground(new java.awt.Color(204, 204, 255));
        jButton_Atras.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton_Atras.setText("ATRAS");
        jButton_Atras.setBorder(null);
        jButton_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AtrasActionPerformed(evt);
            }
        });

        Label_NombreCliente1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Label_NombreCliente1.setText("TIPO");

        Label_DescuentoClienteHabitual.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Label_DescuentoClienteHabitual.setText("DESCUENTO");

        jComboBoxTipoClienteHabitual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtIngresoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Label_CedulaClienteHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_NombreClienteHab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_TelefonoClienteHab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_DescuentoClienteHabitual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_NombreCliente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_NombreClienteHab, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TelefonoClienteHab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_CedulaClienteHab, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_IngresarClienteHab, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_DescuentoClienteHab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTipoClienteHabitual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIngresoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_NombreCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxTipoClienteHabitual)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_NombreClienteHab, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_NombreClienteHab, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_CedulaClienteHab, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_CedulaClienteHab, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_TelefonoClienteHab, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TelefonoClienteHab, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_DescuentoClienteHabitual, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_DescuentoClienteHab, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_IngresarClienteHab, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>                        

    private void jButton_IngresarClienteHabActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        String nombre = jTextField_NombreClienteHab.getText();
        String cedulaStr = jTextField_CedulaClienteHab.getText();
        String descuentoStr = jTextField_DescuentoClienteHab.getText();
        String telefono = jTextField_TelefonoClienteHab.getText();
        String tipoCliente = (String) jComboBoxTipoClienteHabitual.getSelectedItem();
    
        int cedulaInt = Integer.parseInt(cedulaStr);
        BigDecimal descuento = new BigDecimal(descuentoStr);  // Usamos BigDecimal para representar números decimales de alta precisión
    
        String url = "jdbc:postgresql://localhost:5432/ProyectoFinal";
        String usuario = "postgres";
        String contraseña = "Nicolas1118";
    
        String sqlVerificar = "SELECT COUNT(*) FROM cliente WHERE cedula = ?";
        String sqlInsertarCliente = "INSERT INTO cliente (nombre, cedula, telefono) VALUES (?, ?, ?)";
        String sqlInsertarHabitual = "INSERT INTO habitual (codigo_h, descuento, cedula) VALUES (?, ?, ?)";
        String sqlInsertarPersonaNatural = "INSERT INTO persona_natural (codigo_p, codigo_h) VALUES (?, ?)";
        String sqlInsertarCorporativo = "INSERT INTO corporativo (codigo_c, codigo_h) VALUES (?, ?)";
    
        try (Connection conn = DriverManager.getConnection(url, usuario, contraseña)) {
            // Verificar si la cédula ya está registrada
            try (PreparedStatement pstmtVerificar = conn.prepareStatement(sqlVerificar)) {
                pstmtVerificar.setInt(1, cedulaInt);
                ResultSet rs = pstmtVerificar.executeQuery();
                rs.next();
                int count = rs.getInt(1);
    
                if (count > 0) {
                    JOptionPane.showMessageDialog(this, "Error: La cédula ya está registrada", "Error", JOptionPane.ERROR_MESSAGE);
                    return; // Salir del método si la cédula ya existe
                }
            }
    
            // Insertar en la tabla cliente
            try (PreparedStatement pstmtInsertarCliente = conn.prepareStatement(sqlInsertarCliente)) {
                pstmtInsertarCliente.setString(1, nombre);
                pstmtInsertarCliente.setInt(2, cedulaInt);
                pstmtInsertarCliente.setString(3, telefono);
                pstmtInsertarCliente.executeUpdate();
            }
    
            // Insertar en la tabla habitual
            try (PreparedStatement pstmtInsertarHabitual = conn.prepareStatement(sqlInsertarHabitual)) {
                pstmtInsertarHabitual.setInt(1, cedulaInt);
                pstmtInsertarHabitual.setBigDecimal(2, descuento);
                pstmtInsertarHabitual.setInt(3, cedulaInt);
                pstmtInsertarHabitual.executeUpdate();
            }
    
            // Insertar en la tabla correspondiente según el tipo de cliente
            if ("Persona Natural".equals(tipoCliente)) {
                try (PreparedStatement pstmtInsertarPersonaNatural = conn.prepareStatement(sqlInsertarPersonaNatural)) {
                    pstmtInsertarPersonaNatural.setInt(1, cedulaInt);
                    pstmtInsertarPersonaNatural.setInt(2, cedulaInt);
                    pstmtInsertarPersonaNatural.executeUpdate();
                }
            } else if ("Corporativo".equals(tipoCliente)) {
                try (PreparedStatement pstmtInsertarCorporativo = conn.prepareStatement(sqlInsertarCorporativo)) {
                    pstmtInsertarCorporativo.setInt(1, cedulaInt);
                    pstmtInsertarCorporativo.setInt(2, cedulaInt);
                    pstmtInsertarCorporativo.executeUpdate();
                }
            }
    
            JOptionPane.showMessageDialog(this, "Cliente ingresado correctamente");
    
            // Cerrar la ventana de ingreso cliente
            JFrame Recepcionista = new JFrame("Recepcionista");
            Recepcionista.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            Recepcionista.add(new frmDireccionIngresoCliente());
            Recepcionista.pack();
            Recepcionista.setLocationRelativeTo(null);
            Recepcionista.setVisible(true);
    
            JFrame ClienteFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            ClienteFrame.dispose();
    
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al ingresar cliente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
                                                          

    private void jButton_AtrasActionPerformed(java.awt.event.ActionEvent evt) {                                              
        JFrame Administrador = new JFrame("Administrador");
        Administrador.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Administrador.add(new frmDireccionIngresoCliente());
        Administrador.pack();
        Administrador.setLocationRelativeTo(null);
        Administrador.setVisible(true);

        JFrame ClienteFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        ClienteFrame.dispose();
    }                                             


    // Variables declaration - do not modify                     
    private javax.swing.JLabel Label_CedulaClienteHab;
    private javax.swing.JLabel Label_DescuentoClienteHabitual;
    private javax.swing.JLabel Label_NombreCliente1;
    private javax.swing.JLabel Label_NombreClienteHab;
    private javax.swing.JLabel Label_TelefonoClienteHab;
    private javax.swing.JButton jButton_Atras;
    private javax.swing.JButton jButton_IngresarClienteHab;
    private javax.swing.JComboBox<String> jComboBoxTipoClienteHabitual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_CedulaClienteHab;
    private javax.swing.JTextField jTextField_DescuentoClienteHab;
    private javax.swing.JTextField jTextField_NombreClienteHab;
    private javax.swing.JTextField jTextField_TelefonoClienteHab;
    private javax.swing.JLabel txtIngresoCliente;
    // End of variables declaration                   
}
