package SubVentanas;

//import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


/**
 *
 * @author Nicolas
 */
public class frmListadoReservas extends javax.swing.JPanel {

    /**
     * Creates new form frmListadoReservas
     */
    public frmListadoReservas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtListadoReservas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCedulaReserva = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonConsultarReserva = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtListadoReservas.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        txtListadoReservas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtListadoReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagene/favicon.png"))); // NOI18N
        txtListadoReservas.setText("LISTADO RESERVAS");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setText("CEDULA");

        jTextFieldCedulaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaReservaActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonConsultarReserva.setBackground(new java.awt.Color(204, 204, 255));
        jButtonConsultarReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButtonConsultarReserva.setText("CONSULTAR RESERVAS");
        jButtonConsultarReserva.setBorder(null);
        jButtonConsultarReserva.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonConsultarReservaActionPerformed(evt);
            }
        });

        jButtonAtras.setBackground(new java.awt.Color(204, 204, 255));
        jButtonAtras.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButtonAtras.setText("ATRAS");
        jButtonAtras.setBorder(null);
        jButtonAtras.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtListadoReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConsultarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCedulaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtListadoReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCedulaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }                        

    private void jTextFieldCedulaReservaActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    private void jButtonConsultarReservaActionPerformed(java.awt.event.ActionEvent evt) {
        String url = "jdbc:postgresql://localhost:5432/ProyectoFinal";
        String usuario = "postgres";
        String contraseña = "Nicolas1118";
        
        int cedula;
        try {
            cedula = Integer.parseInt(jTextFieldCedulaReserva.getText());  // Convertir la cédula a entero
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número de cédula válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String consultaCliente = "SELECT * FROM cliente WHERE cedula = ?";
        String consultaReserva = "SELECT * FROM reserva WHERE cod_c = ?";
        
        try (Connection conn = DriverManager.getConnection(url, usuario, contraseña);
             PreparedStatement pstmtCliente = conn.prepareStatement(consultaCliente);
             PreparedStatement pstmtReserva = conn.prepareStatement(consultaReserva)) {
             
            pstmtCliente.setInt(1, cedula);
            ResultSet rsCliente = pstmtCliente.executeQuery();
            
            if (!rsCliente.next()) {
                JOptionPane.showMessageDialog(this, "La cédula no se encuentra registrada en la tabla clientes.", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            pstmtReserva.setInt(1, cedula);
            ResultSet rsReserva = pstmtReserva.executeQuery();
            
            StringBuilder resultados = new StringBuilder();
            while (rsReserva.next()) {
                resultados.append("ID Reserva: ").append(rsReserva.getInt("codigo_reserva"))
                          .append("\nCedula: ").append(rsReserva.getInt("cod_c"))
                          .append("\nFecha Reserva: ").append(rsReserva.getDate("fecha_entrada"))
                          .append("\nNumero de Noches: ").append(rsReserva.getInt("num_hab"))
                          .append("\n-------------------------\n");
            }
            
            if (resultados.length() == 0) {
                JOptionPane.showMessageDialog(this, "La cédula no tiene reservas asociadas.", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                jTextArea1.setText(resultados.toString());
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrió un error al consultar las reservas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButtonAtrasActionPerformed(ActionEvent evt) {
        JFrame ListadoReservas = new JFrame("ListadoReservas");
        ListadoReservas.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ListadoReservas.add(new frmInformes());
        ListadoReservas.pack();
        ListadoReservas.setLocationRelativeTo(null);
        ListadoReservas.setVisible(true);

        JFrame Informes = (JFrame) SwingUtilities.getWindowAncestor(this);
        Informes.dispose();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonConsultarReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldCedulaReserva;
    private javax.swing.JLabel txtListadoReservas;
    // End of variables declaration                   
}
